### ISSUE TITLE
Coach reports have unusable/meaningless options, and no tracking of user activity data

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#223]
TODO:
- [x] Clean up cruft from Google Visualizations implementation.
- [x] Dynamically set the range of the y-axis based on user data. Does not currently do this for timeline view.
- [x] Clean up y axis options for Timeline view.
- [x] Create user activity log option for Timeline view.
- [x] Unhardcode pctmastery as the y-axis value for Timeline view.
