### ISSUE TITLE
Placeholder issue for PR code review checklist (to be updated as we think of things)

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3154]
Hubot says: `Please ensure the following things while reviewing this PR:`

- [ ] Tests have been written, and pass
- [ ] Changes have been made to documentation to reflect changes in interface/features
- [ ] Any changes to CSS have been tested on all other pages that might be affected (that use the same class/id names)
- [ ] No significant impacts on startup or page load efficiency are expected/observed. If there are changes expected here, provide a justification in the PR description.
- [ ] Any changes made to models inheriting from `SyncedModel` have been run past @jamalex

**Comment by aronasorman** [comment]
Changed the 4th checkbox to "No significant impacts on startup or page load efficiency are expected/observed. If there are changes expected here, provide a justification in the PR description".

And if we do want to enforce this, we'll want to have a "reference" PC as our benchmark for startup times. Else, I don't think we'll ever catch all the small ways we can increase startup times, unless we want to manually count queries/syscalls/memreads that we have in our code.

And no, @TravisCI, you cannot be our benchmark PC.

**Comment by rtibbles** [comment]
But I got the build time down to 30 minutes in #3160!

**Comment by MCGallaspy** [comment]
We now have a `CONTRIBUTING.md`, is there anything else we can do?

**Comment by benjaoming** [comment]
Issue templates are in place, closing this.

**Comment by benjaoming** [comment]
And so this was our closed issue number 2,500!
