### ISSUE TITLE
Dependency management: Unbundle python-packages

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3403]
# Overview

Currently, KA Lite ships with a directory `python-packages`, each of them have to be unbundled. That means, for some of them to be placed separately, and for others to be bundled with installers or as dynamic dependencies.

**Unbundling**: To remove a package from python-packages and include it as a dependency /or/ to completely remove the package as a dependency and write some new code.

**Scope**: If a package has been modified, we need to remove the causes of the modification from the kalite codebase. If the package has been updated, we should just pin it at its version from previously and schedule an upgrade for later in a separate issue (unless it's really trivial).
- [x] accenting.py #4706
- [x] announcements #4692
- [x] annoying #4690
- [x] async #4691
- [x] cherrypy #4693
- [x] collections_local_copy.py #4711
- [x] contextlib2.py #4712
- [x] dateutil #4264
- [x] debug_toolbar  #3691
- [ ] django
- [x] django_extensions - #3487
- [x] django_snippets #4714 #4822
- [x] docopt.py
- [ ] fle_utils
- [x] git #3784
- [x] gitdb #3785
- [x] httplib2 #4694
- [x] httreplay  #4695
- [x] ifcfg #4696
- [x] importlib #4697
- [x] iso8601 #4698
- [x] kaa
- [x] khanacademy #4699
- [x] khan_api_python #4700
- [x] memory_profiler.py #4701
- [x] mimeparse.py #4702
- [x] mock.py #3690
- [x] _multiprocessing.py #4703
- [x] oauth.py #4700
- [x] pbkdf2.py #4704
- [x] playground #3676
- [x] polib.py #4705
- [x] postmark #3677
- [x] pyasn1 #4707
- [x] pytz #3678
- [x] requests #5138 
- [x] rsa #4707
- [ ] securesync
- [x] six.py #3716
- [x] slugify #4708
- [x] smmap #4709
- [x] south
- [x] tastypie #3825
- [x] unittest2 #3675
- [x] werkzeug #3679
- [x] xlrd #4710
- [x] youtube_dl  #3696
# Offline Installers

It's important that an installer is portable, thus that it can easily be stored for offline usage.

For Mac / Windows, an approach could be to bundle a virtualenv. @ruimalheiro and @cpauya what are your opinions on this?

For Debian/Ubuntu/other Linux variants, it could be to automatically download all dependencies from PyPi and create a separate .deb or likewise that installs them with pip (which would automatically avoid installing them if they're already satisfied).

Once we have removed the first dependency, we can start experimenting with techniques to re-add it using our installers.
# Dynamic installers

Where possible, it's much easier to create dynamic installers. And they are much easier to update.

Since the current main use case is to install KA Lite and then download resources from online repositories, the offline installers are not yet that crucial.
# Virtualenv discussion

KA Lite is ultimately a Django project and not just a Django application. In most cases of deploying a Django project, it's recommended to manage dependencies in a virtualenv. The reasoning is that dependencies are often pinned to avoid version-agnostic solutions and inter-dependent conflicts between third-party apps....

Since KA Lite might be easier to maintain with pinned dependencies, a system-wide installation might be hard for us to keep track of given the long list of third-parties.

So to mend all this, we might add that installers should always ship a virtualenv.

On the other hand, the clear danger of this, is that we drift away from the development of the third-parties, such as the case of the current Django 1.4 dependency.
# Road ahead / scope

To me, it seems intuitive that the list of dependencies is too long. So we could reduce complexity and potential issues and work-load for upgrades simply by avoiding some of these dependencies.

As previously discussed, we should have a clear policy about dependencies -- something that includes not to shoot sparrows with canons.

But this first step is **not** about removing dependencies unless it's easier than unbundling. It's only about removing the `python-packages/` directory and move on from there.

**Comment by cpauya** [comment]
Hi @benjaoming I like the idea of bundling ka-lite in our installers.

We are doing this already with our Mac OSX installer using [PyRun 2.7](http://www.egenix.com/products/python/PyRun/) - I'm now updating it to include setuptools and pip because it was running the minimal Python before.  We did this because of certain issues with OSX's Python and that we wanted to isolate our Python among the user's installed ones as discussed with @aronasorman before.

Also please note that when I run `pyrun-2.7/bin/pip install -r ka-lite/requirements.txt` - it will install to virtualenv's directory instead of PyRun's.  So we need to deactivate virtualenv when using PyRun.

Here's the PR for the WIP: https://github.com/learningequality/installers/pull/11 for reference.

**Comment by benjaoming** [comment]
@cpauya Thanks for feedback! Question: Isn't PyRun already equivalent to a virtualenv? I mean...

> it will install to virtualenv's directory instead of PyRun's

Which virtualenv is this and when was it activated? In case PyRun can already be bundled with its own pip and this installs to the correct PyRun environment, then I think that problems will be over :) So then the installer would just have to 1) Install PyRun 2) Install a kalite.zip source package into the PyRun env. The source package would be a copy of what's on PyPi so later updates can be performed either online by calling from PyRun.. "pip install kalite --upgrade" or "pip install some-updated-kalite-source-package.zip".

**Comment by cpauya** [comment]
Oops, I had an activated virtualenv, then ran pyrun's pip, which resulted to having the package installed on the active virtualenv instead of pyrun's directories.

Yup, PyRun can be bundled with own python version, pip, and packages... you can even move the pyrun directory and it will still run.

**Comment by benjaoming** [comment]
We managed a lot, battle continues in 0.15!

**Comment by MCGallaspy** [comment]
Pinging this: Using our own interpreter (instead of the system's) could offer some advantages for Windows at least. Instead of trying to guess the location of python.exe (or worse, guessing *which* python to use if both Python 2.7 and Python 3.5 are installed) we can control exactly where the interpreter is and what version is used, simplifying some install-time actions.

In contrast to *nix, Windows doesn't have a good way I know of to manage multiple installed pythons or select which system interpreter to use from the command line, since python *may* not be on the user's path (it's optional and disabled by default at install time) *and* because of environment variable length limits in Windows there is a valid reason why we may not wish to insert entries into the user's path ourselves.

**Comment by benjaoming** [comment]
@MCGallaspy Not sure how the comment relates to this?

Regarding the ping: The status is that there are open PRs for unbundling everything, except fle_utils and django whom shall live in kalite.dist as packages and not data... either that, *or* we manage to revert all our changes to django's codebase and migrate to 1.6 :)

**Comment by MCGallaspy** [comment]
I was looking at the "Virtualenv discussion" section, specifically

> So to mend all this, we might add that installers should always ship a virtualenv.

:+1:

**Comment by MCGallaspy** [comment]
Almost done!

**Comment by benjaoming** [comment]
So freaking close!

**Comment by benjaoming** [comment]
Keeping this issue open will not achieve unbundling of `securesync`, `fle_utils` or `django`, so I'm wrapping it up here.
