### ISSUE TITLE
Ship w/ empty content.db, handle blank default installations

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#5318]
## Summary

We ship a broken default content pack (English content.db w/o assessment items or subtitles, means that you can click exercises but they're broken) - that alone is a solid enough reason to stop building this content pack and instead fix KA Lite.

The other reason is the 90 MB of almost meaningless data (unpacked, ~50 MB download size) that we bundle into the source distribution. This used to make sense, but since it's now entirely overwritten by the content pack, it seems like an irresponsible waste of resources IMO.

This means we should auto-redirect to the Manage tab when user hasn't installed any content.db.

Issue about removing en-minimal.zip from content pack maker:
https://github.com/fle-internal/content-pack-maker/issues/40

## TODO

 - [ ] Make tests etc. function with a fixture based on an empty content.db
 - [ ] The whole app should function without ANY content.db at all
 - [ ] Add sensitive messages explaining the lack of a content db
 - [ ] Consolidate the display of installed content pack, as it probably suffers from some adjustments made to accommodate the legacy "minimal" contentpack

**Comment by benjaoming** [comment]
+ the danger of having wrong versions of the bundled English minimal content pack means that there is no "Upgrade" button visible unless we edit metadata on the server Manually. So we can't release without addressing this.

**Comment by benjaoming** [comment]
It seems that the database and possibly also subtitle files are affected by upgrades, I'm suspecting that the pre-bundled minimal content pack is to blame, but should investigate further.

As of now, it seems certain that when I switch from 0.17b2 with the latest full `en` content pack with correct subtitle annotations and to `develop`, I get all the subtitles wrongly annotated, something that looks like a pre-bundled minimal content.db.

**Comment by benjaoming** [comment]
The .whl source files have reduced from `52 MB` til `31 MB`, expecting similar results in debian packages and installers because they contain the source distribution in which the English content.db is overwritten after installation.

It should also have a performance-wise impact because content annotation no longer takes place twice (at first setup, then after content pack installation).

**Comment by benjaoming** [comment]
Fixed in  #5350
