### ISSUE TITLE
Video download robustness improvements

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#5538]
## Summary

 * [x] ~Move fallback using Youtube-dl~ only trigger `download_video` and in case a thumbnail is missing, don't break.
 * [x] Add tests specifically for the youtube-dl part. #5545
 * [x] Ensure that a connection can be cut for up to ~1~ 24 minutes per video without breaking downloads. #5545
 * [ ] Factor `fle_utils` out of everything that has to do with video downloads
 * [x] Non-200 responses or other types of errors resulting in error pages being downloaded as `mp4` files. #5545
 * [x] Downloads that break while downloading should be retried, not removed completely from queue (now retried for ~24 minutes, then retried with youtube-dl) #5545

We have had sporadic missing thumbnails, which is explained in case there is a false positive `URLNotFound` because of connection errors fetching videos or thumbnails would trigger `youtube-dl`.

The following content has been found as an `.mp4` file:

```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
```

**Comment by benjaoming** [comment]
Fixed in #5545!
